import {
  DEFAULT_UNCERTAINTY_SAMPLE_COUNT,
  DEFAULT_UNCERTAINTY_SEED,
  type EditableProjectInputs,
} from "./project-state.ts";

export const EXPERIENCE_MODE_STORAGE_KEY = "kestrel.project.arc54.experience-mode.v1";

export type ExperienceMode = "beginner" | "expert";
export type ProjectTemplateId = "first-flight" | "high-power" | "weather-study" | "ballistic-check";

export type ProjectTemplate = Readonly<{
  id: ProjectTemplateId;
  name: string;
  eyebrow: string;
  description: string;
  audience: string;
  inputs: EditableProjectInputs;
  focus: ReadonlyArray<string>;
}>;

export const PROJECT_TEMPLATES: ReadonlyArray<ProjectTemplate> = [
  {
    id: "first-flight",
    name: "First flight",
    eyebrow: "BEGINNER",
    description: "A compact, recovery-equipped vehicle with conservative inputs for learning the design loop.",
    audience: "Start here",
    inputs: {
      lengthMm: 710,
      diameterMm: 54,
      noseLengthMm: 180,
      noseProfile: "ogive",
      finCount: 3,
      finRootChordMm: 130,
      finTipChordMm: 55,
      finSweepMm: 45,
      finSpanMm: 75,
      finThicknessMm: 3,
      payloadMassKg: 0.16,
      material: "kraft",
      thrustN: 22,
      burnTimeS: 1.65,
      dragCoefficient: 0.52,
      launchSiteName: "ARC 54 synthetic range",
      launchLatitudeDeg: -36.85,
      launchLongitudeDeg: 174.76,
      launchAltitudeM: 80,
      windSpeedMps: 4,
      windAzimuthDeg: 0,
      windProfileLayers: [],
      turbulenceScale: 1,
      weatherSeed: "arc54-weather-v1",
      relativeHumidityPercent: 60,
      surfacePressureHpa: 1004,
      surfaceTemperatureC: 15,
      launchRailEnabled: true,
      launchRailLengthM: 1.2,
      launchRailInclinationDeg: 0,
      launchRailAzimuthDeg: 0,
      recoveryEnabled: true,
      recoveryDelayS: 0,
      recoveryDiameterM: 0.45,
      recoveryMassKg: 0.06,
      recoveryDeploymentSuccessProbability: 0.9,
      recoveryReefingEnabled: false,
      recoveryReefingDurationS: 3,
      recoveryReefingStartAreaFraction: 0.35,
      uncertaintySampleCount: DEFAULT_UNCERTAINTY_SAMPLE_COUNT,
      uncertaintySeed: DEFAULT_UNCERTAINTY_SEED,
      uncertaintyCorrelations: [],
    },
    focus: ["See how CG and CP change with geometry", "Run a first vertical estimate", "Read the uncertainty envelope"],
  },
  {
    id: "high-power",
    name: "High-power study",
    eyebrow: "EXPERT",
    description: "A heavier composite vehicle intended for exploring thrust, dynamic pressure, and recovery tradeoffs.",
    audience: "Trade studies",
    inputs: {
      lengthMm: 1200,
      diameterMm: 75,
      noseLengthMm: 260,
      noseProfile: "ogive",
      finCount: 4,
      finRootChordMm: 210,
      finTipChordMm: 70,
      finSweepMm: 80,
      finSpanMm: 105,
      finThicknessMm: 4,
      payloadMassKg: 0.45,
      material: "fiberglass",
      thrustN: 95,
      burnTimeS: 2.8,
      dragCoefficient: 0.48,
      launchSiteName: "ARC 54 synthetic range",
      launchLatitudeDeg: -36.85,
      launchLongitudeDeg: 174.76,
      launchAltitudeM: 180,
      windSpeedMps: 6,
      windAzimuthDeg: 0,
      windProfileLayers: [],
      turbulenceScale: 1,
      weatherSeed: "arc54-weather-v1",
      relativeHumidityPercent: 45,
      surfacePressureHpa: 995,
      surfaceTemperatureC: 18,
      launchRailEnabled: true,
      launchRailLengthM: 1.5,
      launchRailInclinationDeg: 0,
      launchRailAzimuthDeg: 0,
      recoveryEnabled: true,
      recoveryDelayS: 1,
      recoveryDiameterM: 0.75,
      recoveryMassKg: 0.12,
      recoveryDeploymentSuccessProbability: 0.9,
      recoveryReefingEnabled: false,
      recoveryReefingDurationS: 3,
      recoveryReefingStartAreaFraction: 0.35,
      uncertaintySampleCount: DEFAULT_UNCERTAINTY_SAMPLE_COUNT,
      uncertaintySeed: DEFAULT_UNCERTAINTY_SEED,
      uncertaintyCorrelations: [],
    },
    focus: ["Inspect maximum dynamic pressure", "Compare recovery impact speed", "Use bounded optimization with guardrails"],
  },
  {
    id: "weather-study",
    name: "Weather study",
    eyebrow: "ANALYSIS",
    description: "A moderate vehicle with stronger wind inputs for exploring deterministic turbulence and landing dispersion.",
    audience: "Environment work",
    inputs: {
      lengthMm: 900,
      diameterMm: 60,
      noseLengthMm: 210,
      noseProfile: "elliptical",
      finCount: 3,
      finRootChordMm: 160,
      finTipChordMm: 60,
      finSweepMm: 55,
      finSpanMm: 85,
      finThicknessMm: 3,
      payloadMassKg: 0.3,
      material: "carbon",
      thrustN: 42,
      burnTimeS: 2.2,
      dragCoefficient: 0.6,
      launchSiteName: "ARC 54 synthetic range",
      launchLatitudeDeg: -36.85,
      launchLongitudeDeg: 174.76,
      launchAltitudeM: 150,
      windSpeedMps: 12,
      windAzimuthDeg: 35,
      windProfileLayers: [],
      turbulenceScale: 1.35,
      weatherSeed: "arc54-weather-study-v1",
      relativeHumidityPercent: 70,
      surfacePressureHpa: 997,
      surfaceTemperatureC: 12,
      launchRailEnabled: true,
      launchRailLengthM: 1.2,
      launchRailInclinationDeg: 0,
      launchRailAzimuthDeg: 0,
      recoveryEnabled: true,
      recoveryDelayS: 0.5,
      recoveryDiameterM: 0.6,
      recoveryMassKg: 0.08,
      recoveryDeploymentSuccessProbability: 0.9,
      recoveryReefingEnabled: false,
      recoveryReefingDurationS: 3,
      recoveryReefingStartAreaFraction: 0.35,
      uncertaintySampleCount: DEFAULT_UNCERTAINTY_SAMPLE_COUNT,
      uncertaintySeed: DEFAULT_UNCERTAINTY_SEED,
      uncertaintyCorrelations: [],
    },
    focus: ["Read mean wind and turbulence", "Inspect the landing footprint", "Compare sensitivity drivers"],
  },
  {
    id: "ballistic-check",
    name: "Ballistic check",
    eyebrow: "DIAGNOSTIC",
    description: "A recovery-disabled configuration for understanding the descent baseline and warning system.",
    audience: "Model inspection",
    inputs: {
      lengthMm: 500,
      diameterMm: 40,
      noseLengthMm: 120,
      noseProfile: "conical",
      finCount: 3,
      finRootChordMm: 90,
      finTipChordMm: 30,
      finSweepMm: 25,
      finSpanMm: 55,
      finThicknessMm: 2,
      payloadMassKg: 0.08,
      material: "kraft",
      thrustN: 12,
      burnTimeS: 1.2,
      dragCoefficient: 0.55,
      launchSiteName: "ARC 54 synthetic range",
      launchLatitudeDeg: -36.85,
      launchLongitudeDeg: 174.76,
      launchAltitudeM: 0,
      windSpeedMps: 2,
      windAzimuthDeg: 0,
      windProfileLayers: [],
      turbulenceScale: 0,
      weatherSeed: "arc54-ballistic-v1",
      relativeHumidityPercent: 25,
      surfacePressureHpa: 1013.25,
      surfaceTemperatureC: 15,
      launchRailEnabled: true,
      launchRailLengthM: 0.9,
      launchRailInclinationDeg: 0,
      launchRailAzimuthDeg: 0,
      recoveryEnabled: false,
      recoveryDelayS: 0,
      recoveryDiameterM: 0.4,
      recoveryMassKg: 0.04,
      recoveryDeploymentSuccessProbability: 0.9,
      recoveryReefingEnabled: false,
      recoveryReefingDurationS: 3,
      recoveryReefingStartAreaFraction: 0.35,
      uncertaintySampleCount: DEFAULT_UNCERTAINTY_SAMPLE_COUNT,
      uncertaintySeed: DEFAULT_UNCERTAINTY_SEED,
      uncertaintyCorrelations: [],
    },
    focus: ["See the ballistic descent warning", "Compare recovery and no-recovery states", "Understand model assumptions"],
  },
];

export function findProjectTemplate(id: ProjectTemplateId): ProjectTemplate {
  const template = PROJECT_TEMPLATES.find((candidate) => candidate.id === id);
  if (!template) throw new Error(`Unknown project template: ${id}`);
  return template;
}
